import 'package:flutter_test/flutter_test.dart';

import 'package:context_forge/models/clean_transcript.dart';
import 'package:context_forge/models/transcript_download.dart';
import 'package:context_forge/models/transcript_language.dart';
import 'package:context_forge/models/transcript_track.dart';
import 'package:context_forge/models/video.dart';
import 'package:context_forge/services/output_builder_service.dart';

void main() {
  const service = OutputBuilderService();
  const separator = '--------------------------------------------------';

  final publishedAt1 = DateTime.utc(2025, 1, 15);
  final publishedAt2 = DateTime.utc(2025, 3, 20);
  final createdAt = DateTime.utc(2026, 2, 8);
  final updatedAt = DateTime.utc(2026, 2, 8);

  Video video({
    required String id,
    required String videoId,
    required String url,
    required String title,
    required DateTime publishedAt,
  }) {
    return Video(
      id: id,
      url: url,
      videoId: videoId,
      title: title,
      channelName: 'Tech Channel',
      publishedAt: publishedAt,
      transcriptLanguage: TranscriptLanguage.polish,
      transcriptAvailable: true,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  CleanTranscript transcript(String videoId, String text) {
    return CleanTranscript(
      videoId: videoId,
      track: const TranscriptTrack(
        language: TranscriptLanguage.polish,
        isAutoGenerated: false,
        languageCode: 'pl',
        languageName: 'Polish',
      ),
      text: text,
      original: TranscriptDownload(
        videoId: videoId,
        track: const TranscriptTrack(
          language: TranscriptLanguage.polish,
          isAutoGenerated: false,
          languageCode: 'pl',
          languageName: 'Polish',
        ),
        text: text,
        segments: const [],
      ),
    );
  }

  const prompt = 'Write a newsletter based on the transcripts.';

  group('OutputBuilderService.build', () {
    test('generates complete output with all sections', () {
      final output = service.build(
        selectedPrompt: prompt,
        videos: [
          video(
            id: 'v1',
            videoId: 'abc123',
            url: 'https://www.youtube.com/watch?v=abc123',
            title: 'First Video',
            publishedAt: publishedAt1,
          ),
          video(
            id: 'v2',
            videoId: 'xyz789',
            url: 'https://www.youtube.com/watch?v=xyz789',
            title: 'Second Video',
            publishedAt: publishedAt2,
          ),
        ],
        transcripts: [
          transcript('abc123', 'First transcript text.'),
          transcript('xyz789', 'Second transcript text.'),
        ],
      );

      expect(output, '''$separator

$prompt

(Inspiration

2025-01-15 -> https://www.youtube.com/watch?v=abc123

2025-03-20 -> https://www.youtube.com/watch?v=xyz789

)

Transcript 1

First transcript text.

Transcript 2

Second transcript text.

$separator''');
    });

    test('excludes videos and transcripts that are missing', () {
      final output = service.build(
        selectedPrompt: prompt,
        videos: [
          video(
            id: 'v1',
            videoId: 'abc123',
            url: 'https://www.youtube.com/watch?v=abc123',
            title: 'First Video',
            publishedAt: publishedAt1,
          ),
        ],
        transcripts: [
          transcript('abc123', 'First transcript text.'),
          transcript('missing', '   '),
        ],
      );

      expect(output, '''$separator

$prompt

(Inspiration

2025-01-15 -> https://www.youtube.com/watch?v=abc123

)

Transcript 1

First transcript text.

$separator''');
    });

    test('handles empty video list', () {
      final output = service.build(
        selectedPrompt: prompt,
        videos: const [],
        transcripts: [
          transcript('abc123', 'Only transcript.'),
        ],
      );

      expect(output, '''$separator

$prompt

(Inspiration

)

Transcript 1

Only transcript.

$separator''');
    });
  });
}