import 'package:flutter_test/flutter_test.dart';

import 'package:context_forge/models/transcript_language.dart';
import 'package:context_forge/models/transcript_selection.dart';
import 'package:context_forge/models/transcript_track.dart';
import 'package:context_forge/services/transcript_selection_service.dart';

TranscriptTrack track(
  String code,
  TranscriptLanguage language, {
  bool auto = false,
}) {
  return TranscriptTrack(
    language: language,
    isAutoGenerated: auto,
    languageCode: code,
    languageName: code,
    isTranslatable: false,
  );
}

void main() {
  const service = TranscriptSelectionService();

  TranscriptSelected expectSelected(TranscriptSelectionResult r) {
    expect(r, isA<TranscriptSelected>());
    return r as TranscriptSelected;
  }

  group('TranscriptSelectionService.select', () {
    test('selects manual Polish over all others', () {
      final result = expectSelected(service.select([
        track('en', TranscriptLanguage.english, auto: true),
        track('pl', TranscriptLanguage.polish, auto: true),
        track('en', TranscriptLanguage.english),
        track('pl', TranscriptLanguage.polish),
        track('de', TranscriptLanguage.other),
      ]));

      expect(result.track.languageCode, 'pl');
      expect(result.track.isAutoGenerated, isFalse);
      expect(result.reason, TranscriptSelectionReason.manualPolish);
      expect(result.priority, TranscriptPriority.manualPolish);
      expect(result.priority.rank, 1);
    });

    test('selects auto Polish when manual Polish missing', () {
      final result = expectSelected(service.select([
        track('en', TranscriptLanguage.english),
        track('pl', TranscriptLanguage.polish, auto: true),
        track('fr', TranscriptLanguage.other),
      ]));

      expect(result.track.languageCode, 'pl');
      expect(result.track.isAutoGenerated, isTrue);
      expect(result.reason, TranscriptSelectionReason.autoPolish);
      expect(result.priority, TranscriptPriority.autoPolish);
    });

    test('selects manual English when no Polish available', () {
      final result = expectSelected(service.select([
        track('en', TranscriptLanguage.english, auto: true),
        track('en', TranscriptLanguage.english),
      ]));

      expect(result.track.languageCode, 'en');
      expect(result.track.isAutoGenerated, isFalse);
      expect(result.reason, TranscriptSelectionReason.manualEnglish);
    });

    test('selects auto English when manual English unavailable', () {
      final result = expectSelected(service.select([
        track('en', TranscriptLanguage.english, auto: true),
        track('de', TranscriptLanguage.other),
      ]));

      expect(result.track.languageCode, 'en');
      expect(result.track.isAutoGenerated, isTrue);
      expect(result.reason, TranscriptSelectionReason.autoEnglish);
    });

    test('falls back to any other manual transcript', () {
      final result = expectSelected(service.select([
        track('de', TranscriptLanguage.other, auto: true),
        track('es', TranscriptLanguage.other),
      ]));

      expect(result.track.languageCode, 'es');
      expect(result.track.isAutoGenerated, isFalse);
      expect(result.reason, TranscriptSelectionReason.otherManual);
    });

    test('falls back to any other auto-generated transcript', () {
      final result = expectSelected(service.select([
        track('de', TranscriptLanguage.other, auto: true),
      ]));

      expect(result.track.languageCode, 'de');
      expect(result.track.isAutoGenerated, isTrue);
      expect(result.reason, TranscriptSelectionReason.otherAuto);
    });

    test('returns TranscriptUnavailable when no transcripts', () {
      final result = service.select(const []);
      expect(result, isA<TranscriptUnavailable>());
    });

    test('is deterministic for mixed lists with duplicate priorities', () {
      final tracks = [
        track('de', TranscriptLanguage.other),
        track('pl', TranscriptLanguage.polish, auto: true),
        track('en', TranscriptLanguage.english, auto: true),
        track('pl', TranscriptLanguage.polish),
        track('fr', TranscriptLanguage.other, auto: true),
      ];

      const runs = 50;
      for (var i = 0; i < runs; i++) {
        final result = expectSelected(service.select(tracks));
        expect(result.track.languageCode, 'pl');
        expect(result.track.isAutoGenerated, isFalse);
        expect(result.reason, TranscriptSelectionReason.manualPolish);
      }
    });

    test('ignores unclassifiable tracks and falls back gracefully', () {
      final result = expectSelected(service.select([
        track('xx', TranscriptLanguage.none),
        track('en', TranscriptLanguage.english),
      ]));
      expect(result.reason, TranscriptSelectionReason.manualEnglish);
    });
  });
}