import 'package:flutter_test/flutter_test.dart';

import 'package:context_forge/models/clean_transcript.dart';
import 'package:context_forge/models/transcript_download.dart';
import 'package:context_forge/models/transcript_language.dart';
import 'package:context_forge/models/transcript_track.dart';
import 'package:context_forge/services/transcript_cleanup_service.dart';

void main() {
  const service = TranscriptCleanupService();

  TranscriptDownload download(String text) {
    return TranscriptDownload(
      videoId: 'abc123',
      track: const TranscriptTrack(
        language: TranscriptLanguage.polish,
        isAutoGenerated: false,
        languageCode: 'pl',
        languageName: 'Polish',
      ),
      text: text,
      segments: const [],
    );
  }

  group('TranscriptCleanupService.clean', () {
    test('removes timestamp lines', () {
      final raw = '[00:12]\nHello world\n[00:15]\nGoodbye\n'
          '00:20\nSecond paragraph\n00:20:15 -> 00:20:30\nThird\n'
          '[00:25] -> [00:28]\nLast';
      final result = service.clean(download(raw));
      expect(result.text, 'Hello world\nGoodbye\n'
          'Second paragraph\nThird\nLast');
    });

    test('removes empty lines', () {
      final raw = 'First line\n\n\nSecond line\n\t\nThird line';
      final result = service.clean(download(raw));
      expect(result.text, 'First line\nSecond line\nThird line');
    });

    test('normalizes whitespace within lines', () {
      final raw = 'Hello    world\nThis   is   a   test';
      final result = service.clean(download(raw));
      expect(result.text, 'Hello world\nThis is a test');
    });

    test('handles empty transcript', () {
      final result = service.clean(download(''));
      expect(result.text, '');
    });

    test('preserves already clean transcript', () {
      final raw = 'Line one\nLine two\nLine three';
      final result = service.clean(download(raw));
      expect(result.text, raw);
    });

    test('handles mixed formatting deterministically', () {
      final raw = '[00:00]  Intro  text\n\n'
          'More text\n[00:05]\n'
          '   Another line   \n\n'
          '00:10 -> 00:15\nFinal';
      final first = service.clean(download(raw));
      final second = service.clean(download(raw));
      expect(first, second);
      expect(first.text, 'Intro text\nMore text\nAnother line\nFinal');
    });

    test('preserves original transcript on result', () {
      final original = download('Some text');
      final result = service.clean(original);
      expect(result.original, same(original));
      expect(result, isA<CleanTranscript>());
      expect(result.videoId, 'abc123');
      expect(result.track.languageCode, 'pl');
    });

    test('preserves paragraph breaks', () {
      final raw = 'Paragraph one\n\nParagraph two\n\nParagraph three';
      final result = service.clean(download(raw));
      expect(result.text, 'Paragraph one\n\nParagraph two\n\nParagraph three');
    });

    test('never translates or summarizes', () {
      final raw = 'Czesc swiecie\nTo jest test\n';
      final result = service.clean(download(raw));
      expect(result.text, 'Czesc swiecie\nTo jest test');
    });
  });
}
