import 'package:flutter_test/flutter_test.dart';

import 'package:context_forge/exceptions/youtube_exceptions.dart';
import 'package:context_forge/models/transcript_language.dart';
import 'package:context_forge/models/transcript_track.dart';
import 'package:context_forge/providers/youtube_provider.dart';
import 'package:context_forge/providers/youtube_transcript.dart';
import 'package:context_forge/providers/youtube_transcript_info.dart';
import 'package:context_forge/providers/youtube_video_metadata.dart';
import 'package:context_forge/services/transcript_service.dart';

class _FakeProvider implements YoutubeProvider {
  _FakeProvider({this.tracks = const [], this.error});

  final List<YoutubeTranscriptInfo> tracks;
  final Object? error;

  @override
  Future<YoutubeVideoMetadata?> getVideoMetadata(String videoId) async => null;

  @override
  Future<List<YoutubeTranscriptInfo>> getAvailableTranscripts(
    String videoId,
  ) async {
    if (error != null) throw error!;
    return tracks;
  }

  @override
  Future<YoutubeTranscript?> downloadTranscript(
    String videoId,
    YoutubeTranscriptInfo info,
  ) async => null;
}

void main() {
  group('TranscriptService.getAvailableTranscripts', () {
    test('maps provider DTOs to domain tracks', () async {
      final service = TranscriptService(
        provider: _FakeProvider(tracks: [
          YoutubeTranscriptInfo(
            language: TranscriptLanguage.polish,
            isManual: true,
            languageName: 'Polish',
            languageCode: 'pl',
            isTranslatable: false,
          ),
        ]),
      );

      final tracks = await service.getAvailableTranscripts('abc123');
      expect(tracks, hasLength(1));
      final t = tracks.single;
      expect(t.language, TranscriptLanguage.polish);
      expect(t.isAutoGenerated, isFalse);
      expect(t.languageCode, 'pl');
      expect(t.languageName, 'Polish');
      expect(t.isTranslatable, isFalse);
      expect(t, isA<TranscriptTrack>());
    });

    test('maps auto-generated transcript', () async {
      final service = TranscriptService(
        provider: _FakeProvider(tracks: [
          YoutubeTranscriptInfo(
            language: TranscriptLanguage.englishAuto,
            isManual: false,
            languageName: 'English (auto)',
            languageCode: 'en',
            isTranslatable: true,
          ),
        ]),
      );

      final tracks = await service.getAvailableTranscripts('abc123');
      expect(tracks.single.isAutoGenerated, isTrue);
      expect(tracks.single.language, TranscriptLanguage.englishAuto);
      expect(tracks.single.isTranslatable, isTrue);
    });

    test('returns empty list when no transcripts available', () async {
      final service = TranscriptService(
        provider: _FakeProvider(tracks: const []),
      );
      final tracks = await service.getAvailableTranscripts('abc123');
      expect(tracks, isEmpty);
    });

    test('discoverTranscriptTracks throws when none available', () async {
      final service = TranscriptService(
        provider: _FakeProvider(tracks: const []),
      );
      expect(
        () => service.discoverTranscriptTracks('abc123'),
        throwsA(isA<TranscriptsUnavailableException>()),
      );
    });

    test('propagates unavailable video exception', () async {
      final service = TranscriptService(
        provider: _FakeProvider(
          error: const YoutubeVideoUnavailableException('gone'),
        ),
      );
      expect(
        () => service.getAvailableTranscripts('abc123'),
        throwsA(isA<YoutubeVideoUnavailableException>()),
      );
    });

    test('propagates network failure', () async {
      final service = TranscriptService(
        provider: _FakeProvider(error: Exception('connection')),
      );
      expect(
        () => service.getAvailableTranscripts('abc123'),
        throwsA(isA<Exception>()),
      );
    });
  });
}