import '../exceptions/youtube_exceptions.dart';
import '../models/transcript_download.dart';
import '../models/transcript_track.dart';
import '../providers/youtube_provider.dart';
import '../providers/youtube_transcript.dart';
import '../providers/youtube_transcript_info.dart';

/// Application service for transcript domain workflows.
///
/// Responsibility: discover available transcript tracks for a video and
/// download the selected track. Provider DTOs are mapped into domain models
/// before leaving the provider layer (ADR-009).
class TranscriptService {
  TranscriptService({required this.provider});

  final YoutubeProvider provider;

  /// Returns the available transcript tracks for [videoId].
  ///
  /// - Returns an empty list when no transcripts are available
  ///   (translates provider empty result to [TranscriptsUnavailableException]
  ///   tolerant path is kept: callers decide; see [discoverTranscriptTracks]).
  Future<List<TranscriptTrack>> getAvailableTranscripts(String videoId) async {
    final dtoTracks = await provider.getAvailableTranscripts(videoId);
    return [
      for (final t in dtoTracks)
        TranscriptTrack(
          language: t.language,
          isAutoGenerated: !t.isManual,
          languageCode: t.languageCode,
          languageName: t.languageName,
          isTranslatable: t.isTranslatable,
        ),
    ];
  }

  /// Convenience wrapper that throws [TranscriptsUnavailableException]
  /// when no tracks exist.
  Future<List<TranscriptTrack>> discoverTranscriptTracks(String videoId) async {
    final tracks = await getAvailableTranscripts(videoId);
    if (tracks.isEmpty) {
      throw TranscriptsUnavailableException(
        'No transcripts available for video "$videoId".',
      );
    }
    return tracks;
  }

  /// Downloads the transcript for [videoId] using the given [track].
  ///
  /// Returns a [TranscriptDownload] containing the plain transcript text
  /// (segments joined without timestamps) together with the raw timestamped
  /// segments for later cleaning.
  ///
  /// Throws:
  /// - [TranscriptsUnavailableException] when the track cannot be downloaded.
  /// - [YoutubeVideoUnavailableException] when the video is unavailable.
  /// - [YoutubeNetworkException] when a network or provider failure occurs.
  Future<TranscriptDownload> downloadTranscript(
    String videoId,
    TranscriptTrack track,
  ) async {
    final info = _toDto(track);
    final transcript = await provider.downloadTranscript(videoId, info);
    if (transcript == null) {
      throw TranscriptsUnavailableException(
        'Transcript "${track.languageName}" is unavailable for video '
        '"$videoId".',
      );
    }
    return _toDomain(videoId, track, transcript);
  }

  YoutubeTranscriptInfo _toDto(TranscriptTrack track) {
    return YoutubeTranscriptInfo(
      language: track.language,
      isManual: !track.isAutoGenerated,
      languageName: track.languageName,
      languageCode: track.languageCode,
      isTranslatable: track.isTranslatable,
    );
  }

  TranscriptDownload _toDomain(
    String videoId,
    TranscriptTrack track,
    YoutubeTranscript transcript,
  ) {
    return TranscriptDownload(
      videoId: videoId,
      track: track,
      text: [
        for (final s in transcript.segments) s.text,
      ].join(' '),
      segments: [
        for (final s in transcript.segments)
          TranscriptSegment(
            offset: s.offset,
            duration: s.duration,
            text: s.text,
          ),
      ],
    );
  }
}
