import '../exceptions/youtube_exceptions.dart';
import '../models/transcript_track.dart';
import '../providers/youtube_provider.dart';

/// Application service for transcript domain workflows.
///
/// Responsibility (this phase): discover available transcript tracks for a
/// video. Mapped from provider DTOs into domain [TranscriptTrack] models
/// (ADR-009). No transcript text download.
class TranscriptService {
  TranscriptService({required this.provider});

  final YoutubeProvider provider;

  /// Returns the available transcript tracks for [videoId].
  ///
  /// - Returns an empty list when no transcripts are available
  ///   (translates provider empty result to [TranscriptsUnavailableException]
  ///   tolerant path is kept: callers decide; see [discoverTranscriptTracks]).
  Future<List<TranscriptTrack>> getAvailableTranscripts(String videoId) async {
    final dtoTracks = await provider.getAvailableTranscripts(videoId);
    return [
      for (final t in dtoTracks)
        TranscriptTrack(
          language: t.language,
          isAutoGenerated: !t.isManual,
          languageCode: t.languageCode,
          languageName: t.languageName,
          isTranslatable: t.isTranslatable,
        ),
    ];
  }

  /// Convenience wrapper that throws [TranscriptsUnavailableException]
  /// when no tracks exist.
  Future<List<TranscriptTrack>> discoverTranscriptTracks(String videoId) async {
    final tracks = await getAvailableTranscripts(videoId);
    if (tracks.isEmpty) {
      throw TranscriptsUnavailableException(
        'No transcripts available for video "$videoId".',
      );
    }
    return tracks;
  }
}