import 'package:flutter/foundation.dart';

import '../models/transcript_language.dart';
import '../models/transcript_selection.dart';
import '../models/transcript_track.dart';

/// Pure transcript selection service.
///
/// Only responsibility: choose the best transcript track from a list of
/// domain [TranscriptTrack]s. No networking, no provider access, no
/// transcript download. Deterministic: the first track with the best
/// priority (insertion order) wins.
class TranscriptSelectionService {
  const TranscriptSelectionService();

  TranscriptSelectionResult select(List<TranscriptTrack> tracks) {
    TranscriptTrack? best;
    TranscriptPriority? bestPriority;
    TranscriptSelectionReason? bestReason;

    for (final track in tracks) {
      final classified = _classify(track);
      if (classified == null) continue;
      final (priority, reason) = classified;
      if (bestPriority == null || priority.rank < bestPriority.rank) {
        best = track;
        bestPriority = priority;
        bestReason = reason;
      }
    }

    if (best == null || bestPriority == null || bestReason == null) {
      debugPrint('[TranscriptSelectionService] Selection: '
          'no transcript available (${tracks.length} track(s) provided)');
      return const TranscriptUnavailable();
    }
    debugPrint('[TranscriptSelectionService] Selected: '
        'language=${best.language.name}, auto=${best.isAutoGenerated}, '
        'code=${best.languageCode}, reason=${bestReason.name}');
    return TranscriptSelected(
      track: best,
      reason: bestReason,
      priority: bestPriority,
    );
  }

  (TranscriptPriority, TranscriptSelectionReason)? _classify(
    TranscriptTrack track,
  ) {
    final isAuto = track.isAutoGenerated;
    return switch (track.language) {
      TranscriptLanguage.polish => isAuto
          ? (TranscriptPriority.autoPolish, TranscriptSelectionReason.autoPolish)
          : (TranscriptPriority.manualPolish,
              TranscriptSelectionReason.manualPolish),
      TranscriptLanguage.polishAuto =>
        (TranscriptPriority.autoPolish, TranscriptSelectionReason.autoPolish),
      TranscriptLanguage.english => isAuto
          ? (TranscriptPriority.autoEnglish,
              TranscriptSelectionReason.autoEnglish)
          : (TranscriptPriority.manualEnglish,
              TranscriptSelectionReason.manualEnglish),
      TranscriptLanguage.englishAuto =>
        (TranscriptPriority.autoEnglish, TranscriptSelectionReason.autoEnglish),
      TranscriptLanguage.other || TranscriptLanguage.none => isAuto
          ? (TranscriptPriority.otherAuto, TranscriptSelectionReason.otherAuto)
          : (TranscriptPriority.otherManual,
              TranscriptSelectionReason.otherManual),
    };
  }
}