import 'transcript_language.dart';

/// Domain model describing an available transcript track.
///
/// This is the domain representation used by the application layer
/// (ADR-009): provider DTOs are mapped into this model before leaving
/// the provider layer. Discovery only — no transcript text.
class TranscriptTrack {
  const TranscriptTrack({
    required this.language,
    required this.isAutoGenerated,
    required this.languageCode,
    required this.languageName,
    this.isTranslatable = false,
  });

  /// Preferred transcript language/origin.
  final TranscriptLanguage language;

  /// Whether the track was automatically generated.
  final bool isAutoGenerated;

  /// ISO 639-1 language code (e.g., "pl", "en").
  final String languageCode;

  /// Human-readable language name.
  final String languageName;

  /// Whether the track can be auto-translated (defaults to false when
  /// the provider does not expose this information).
  final bool isTranslatable;

  TranscriptTrack copyWith({
    TranscriptLanguage? language,
    bool? isAutoGenerated,
    String? languageCode,
    String? languageName,
    bool? isTranslatable,
  }) {
    return TranscriptTrack(
      language: language ?? this.language,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      languageCode: languageCode ?? this.languageCode,
      languageName: languageName ?? this.languageName,
      isTranslatable: isTranslatable ?? this.isTranslatable,
    );
  }

  @override
  bool operator ==(Object other) {
    return other is TranscriptTrack &&
        other.language == language &&
        other.isAutoGenerated == isAutoGenerated &&
        other.languageCode == languageCode &&
        other.languageName == languageName &&
        other.isTranslatable == isTranslatable;
  }

  @override
  int get hashCode =>
      Object.hash(language, isAutoGenerated, languageCode, languageName, isTranslatable);

  @override
  String toString() =>
      'TranscriptTrack(language: $language, isAutoGenerated: $isAutoGenerated, '
      'code: $languageCode, name: $languageName, translatable: $isTranslatable)';
}